### ISSUE TITLE
Can any one have simple demo for Snowplow (snowplow-nodejs-tracker) event tracking on page click and how  we catch them in object

### ISSUE THREAD

**Issue by pawanpatil08** [snowplow/snowplow-nodejs-tracker#38]
I want to capture some user events with snowplow-tracker like If user search on page then detail what he search then how much result occurred and like other

**Comment by chuwy** [comment]
Hello @pawanpatil08, please direct support question to [our forums](https://discourse.snowplowanalytics.com/).

[Technical documantion](https://github.com/snowplow/snowplow/wiki/Node.js-Tracker#page-view) is available on our wiki.
