### ISSUE TITLE
Has this project been deprecated?

### ISSUE THREAD

**Issue by clark-pan** [snowplow/snowplow-nodejs-tracker#40]
It looks like there hasn't been a commit since 2017.

Since then, the snowplow-javascript-core project has moved on a fair amount.

I'm happy to try and update the the dependency, but just want to know if I should be doing it in this project.

**Comment by chuwy** [comment]
Hi @clark-pan, no we don't have plans to deprecate any trackers, just probably Node.js tracker was not on demand really. PRs are always welcome!

**Comment by clark-pan** [comment]
Cool. Opened a PR. https://github.com/snowplow/snowplow-nodejs-tracker/pulls
