### ISSUE TITLE
Add Coveralls code coverage button to README

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-nodejs-tracker#8]

**Comment by fblundun** [comment]
[This](https://strongloop.com/strongblog/npm-modules-travis-coveralls/) is a helpful guide to implementing Coveralls.

**Comment by fblundun** [comment]
@alexanderdean - could you enable Coveralls for this repository please?

**Comment by jbeemster** [comment]
I switched it on for you @fblundun

**Comment by fblundun** [comment]
Thanks @jbeemster !
